 * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [18/Sep/2018 19:51:29] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 401 -
127.0.0.1 - - [18/Sep/2018 19:51:29] "GET /users/hosts/zone/ HTTP/1.1" 401 -
127.0.0.1 - - [18/Sep/2018 19:51:31] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:51:31] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:01] "GET /account/users/?page=1&name= HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:01] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:01] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:03] "GET /account/users/?page=1&name= HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:03] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:31] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:41] "POST /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:42] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:52:45] "GET /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:53:27] "POST /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:53:30] "GET /account/users/?page=1&name= HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:53:30] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:53:56] "POST /account/users/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:53:56] "GET /account/users/?page=1&name= HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:54:01] "GET /account/users/logout/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:54:06] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:54:07] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:54:09] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:54:09] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:54:11] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:54:11] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:58:33] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:58:33] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:59:09] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:59:09] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:59:14] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:59:14] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:59:17] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 19:59:17] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:00:51] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:00:51] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:00:56] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:00:56] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:04:01] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:04:01] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:04:05] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:04:05] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:04:07] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:04:07] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:06:53] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:06:53] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:06:58] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:06:58] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:07:00] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:07:00] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:07:02] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:07:02] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:16] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:16] "GET /users/hosts/zone/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [18/Sep/2018 20:10:26] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 403 -
127.0.0.1 - - [18/Sep/2018 20:10:26] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:28] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:28] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:31] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 403 -
127.0.0.1 - - [18/Sep/2018 20:10:31] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:34] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:34] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:36] "GET /schedule/jobs/?page=1&job_group= HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:36] "GET /schedule/jobs/groups/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:39] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:39] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:42] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 403 -
127.0.0.1 - - [18/Sep/2018 20:10:42] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:52] "GET /account/users/logout/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:54] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:55] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:10:57] "GET /account/users/logout/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:11:00] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:11:00] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:11:03] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 403 -
127.0.0.1 - - [18/Sep/2018 20:11:03] "GET /users/hosts/zone/ HTTP/1.1" 200 -
172.16.6.253 - - [18/Sep/2018 20:11:56] "GET /users/hosts/?page=1 HTTP/1.1" 401 -
172.16.6.253 - - [18/Sep/2018 20:12:34] "GET /users/hosts/?page=1 HTTP/1.1" 403 -
172.16.6.253 - - [18/Sep/2018 20:13:22] "GET /users/hosts/ HTTP/1.1" 403 -
127.0.0.1 - - [18/Sep/2018 20:14:04] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:14:06] "GET /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:15:43] "GET /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:15:48] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:15:50] "GET /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:16:47] "GET /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:16:53] "GET /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:17:13] "POST /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:17:19] "GET /account/users/?page=1&name= HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:17:19] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:17:23] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:17:23] "GET /users/hosts/zone/ HTTP/1.1" 200 -
172.16.6.253 - - [18/Sep/2018 20:17:33] "GET /users/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:17:41] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:17:41] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:18:50] "POST /assets/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:18:50] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:18:50] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:18:52] "GET /assets/hosts/1/valid HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:00] "POST /assets/hosts/1/valid HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:05] "GET /assets/hosts/1/extend/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:06] "GET /assets/hosts/1/extend/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:10] "GET /assets/hosts/1/extend/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:13] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:13] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:15] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:15] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:19] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:19] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:29] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%E5%85%AC%E5%8F%B8%E7%8E%AF%E5%A2%83%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:30] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%E5%85%AC%E5%8F%B8%E7%8E%AF%E5%A2%83%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:33] "GET /users/hosts/1/valid HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:19:49] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:20:04] "GET /users/hosts/1/extend/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:20:06] "GET /users/hosts/1/extend/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:20:07] "GET /users/hosts/1/extend/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': '公司环境'}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': '公司环境'}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
172.16.6.253 - - [18/Sep/2018 20:35:12] "GET /users/hosts/ HTTP/1.1" 200 -
172.16.6.253 - - [18/Sep/2018 20:35:24] "GET /users/zone/ HTTP/1.1" 404 -
172.16.6.253 - - [18/Sep/2018 20:36:03] "GET /users/zone/ HTTP/1.1" 404 -
172.16.6.253 - - [18/Sep/2018 20:36:18] "GET /users/zone/ HTTP/1.1" 404 -
172.16.6.253 - - [18/Sep/2018 20:36:31] "GET /assets/zone/ HTTP/1.1" 404 -
172.16.6.253 - - [18/Sep/2018 20:36:57] "GET /users/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:40:15] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:40:15] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:40:17] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:40:17] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:40:33] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:40:33] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:41:59] "GET /assets/hosts/1/extend/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:42:00] "GET /assets/hosts/1/extend/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:42:01] "GET /assets/hosts/1/extend/ HTTP/1.1" 200 -
172.16.6.253 - - [18/Sep/2018 20:43:28] "GET /users/hosts/zone HTTP/1.1" 301 -
172.16.6.253 - - [18/Sep/2018 20:43:28] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:44:10] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:44:10] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:44:14] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:44:14] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:45:47] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:45:47] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:47:31] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:47:31] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:47:33] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:47:33] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:47:56] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:47:56] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:50:28] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:50:28] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:53:55] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:53:55] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:56:30] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [18/Sep/2018 20:56:30] "GET /users/hosts/zone/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    users.register_blueprint(app)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/__init__.py", line 6, in register_blueprint
    app.register_blueprint(host.blueprint, url_prefix='/users/hosts')
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 951, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/blueprints.py", line 154, in register
    deferred(state)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/blueprints.py", line 173, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1051, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: apps.users.host.fetch_groups

usage: manage.py <command>

command:
    init_db         初始化数据库
    create_admin    创建管理员账户
    enable_admin    启用管理员账户，用于登录失败次数过多账户被禁用时使用
    
 * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [19/Sep/2018 10:09:12] "GET /home/ HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:09:19] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:09:19] "GET /home/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:09:23] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:09:23] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:09:23] "GET /users/hosts/type/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:11:38] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:11:38] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:11:38] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:12:21] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:12:21] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:12:23] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:12:23] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:12:23] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:20] "GET /home/ HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:13:22] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:22] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:32] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:42] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:42] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:48] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:51] "GET /account/users/?page=1&name= HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:51] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:51] "GET /account/roles/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:13:53] "GET /account/roles/1/permissions HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:15:56] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:15:58] "GET /account/users/logout/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:16:01] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:16:02] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:17:57] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:17:57] "GET /assets/hosts/zone/ HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:17:59] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:17:59] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:18:09] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:18:09] "GET /users/hosts/zone/ HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:18:09] "GET /users/hosts/type/ HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:18:15] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:18:15] "GET /home/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:18:18] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:18:18] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:18:18] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:28] "GET /users/hosts/type/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:20:28] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:28] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:35] "GET /account/users/logout/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:38] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:39] "GET /home/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:20:41] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:41] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:41] "GET /users/hosts/type/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:20:59] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:59] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:20:59] "GET /users/hosts/type/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 29, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:21:20] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:21:20] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:21:20] "GET /users/hosts/type/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 25, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:22:33] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:22:33] "GET /users/hosts/zone/ HTTP/1.1" 404 -
127.0.0.1 - - [19/Sep/2018 10:22:33] "GET /users/hosts/type/ HTTP/1.1" 404 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 25, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:23:14] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:23:14] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:23:14] "GET /users/hosts/type/ HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 10:24:04] "GET /users/hosts/type/ HTTP/1.1" 401 -
172.16.6.253 - - [19/Sep/2018 10:24:22] "GET /users/hosts/type/ HTTP/1.1" 401 -
172.16.6.253 - - [19/Sep/2018 10:24:29] "GET /users/hosts/type/ HTTP/1.1" 401 -
172.16.6.253 - - [19/Sep/2018 10:24:41] "GET /users/hosts/type/ HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 10:24:48] "GET /users/hosts/zone/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 25, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
127.0.0.1 - - [19/Sep/2018 10:25:15] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:25:15] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:25:15] "GET /users/hosts/type/ HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 10:26:17] "GET /users/hosts/zone/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 25, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
172.16.6.253 - - [19/Sep/2018 10:26:23] "GET /users/hosts/ HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 10:27:26] "GET /users/hosts/1 HTTP/1.1" 405 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 25, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
172.16.6.253 - - [19/Sep/2018 10:27:37] "GET /users/hosts/?page=1 HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'User'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 25, in get
    if form.User.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'User'
172.16.6.253 - - [19/Sep/2018 10:27:46] "GET /users/hosts/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
name 'Host' is not defined
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 43, in get
    host_data = Host.query
NameError: name 'Host' is not defined
172.16.6.253 - - [19/Sep/2018 10:29:04] "GET /users/hosts/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
'Host'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 47, in get
    if form.Host.query.get('name_field'):
  File "/opt/samba/xdata/xdata/xdata_api/libs/tools.py", line 61, in __getattr__
    return self.__getitem__(item)
KeyError: 'Host'
172.16.6.253 - - [19/Sep/2018 10:29:28] "GET /users/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:29:41] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:29:41] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:29:48] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:29:48] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:30:02] "GET /assets/hosts_exec/tpl/?page=1&tpl_query=%7B%22name_field%22:%22%22,%22type_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:30:02] "GET /assets/hosts_exec/tpl_type HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:30:07] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:30:07] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:30:11] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [19/Sep/2018 10:31:45] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:31:45] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:31:45] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:31:47] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:31:47] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:31:47] "GET /users/hosts/type/ HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 10:31:51] "GET /users/hosts/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [19/Sep/2018 10:32:49] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:32:49] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:32:49] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:32:55] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:32:55] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:32:55] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:32:59] "GET /users/hosts/1/extend/ HTTP/1.1" 404 -
127.0.0.1 - - [19/Sep/2018 10:33:01] "GET /users/hosts/1/extend/ HTTP/1.1" 404 -
172.16.6.253 - - [19/Sep/2018 10:33:04] "GET /users/hosts/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [19/Sep/2018 10:33:50] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:33:50] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:33:50] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:34:34] "POST /users/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:34:34] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:34:34] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:34:34] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:03] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:03] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:03] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:03] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:35:03] "GET /users/hosts/zone/ HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:35:03] "GET /users/hosts/type/ HTTP/1.1" 401 -
127.0.0.1 - - [19/Sep/2018 10:35:09] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:09] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:09] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:14] "GET /users/hosts/4/extend/ HTTP/1.1" 404 -
127.0.0.1 - - [19/Sep/2018 10:35:19] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%E5%8D%8E%E4%B8%9C1%E5%8C%BA%22%7D HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
(pymysql.err.InternalError) (1366, "Incorrect integer value: 'ddd' for column 'db_port' at row 1") [SQL: 'INSERT INTO user_hosts (name, `desc`, type, zone, db_host, db_user, db_password, db_port) VALUES (%(name)s, %(desc)s, %(type)s, %(zone)s, %(db_host)s, %(db_user)s, %(db_password)s, %(db_port)s)'] [parameters: {'name': 'sss', 'desc': 'ddd', 'type': 'MYSQL', 'zone': '华东1区', 'db_host': 'ddd', 'db_user': 'ddd', 'db_password': 'ddd', 'db_port': 'ddd'}]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1366, "Incorrect integer value: 'ddd' for column 'db_port' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 65, in post
    host.save()
  File "/opt/samba/xdata/xdata/xdata_api/libs/model.py", line 20, in save
    db_session_commit()
  File "/opt/samba/xdata/xdata/xdata_api/libs/model.py", line 6, in db_session_commit
    db.session.commit()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1366, "Incorrect integer value: 'ddd' for column 'db_port' at row 1") [SQL: 'INSERT INTO user_hosts (name, `desc`, type, zone, db_host, db_user, db_password, db_port) VALUES (%(name)s, %(desc)s, %(type)s, %(zone)s, %(db_host)s, %(db_user)s, %(db_password)s, %(db_port)s)'] [parameters: {'name': 'sss', 'desc': 'ddd', 'type': 'MYSQL', 'zone': '华东1区', 'db_host': 'ddd', 'db_user': 'ddd', 'db_password': 'ddd', 'db_port': 'ddd'}]
127.0.0.1 - - [19/Sep/2018 10:35:48] "POST /users/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:56] "POST /users/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:56] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%E5%8D%8E%E4%B8%9C1%E5%8C%BA%22,%22type_field%22:%22MYSQL%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:56] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:35:56] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:27] "PUT /users/hosts/5 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:27] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%E5%8D%8E%E4%B8%9C1%E5%8C%BA%22,%22type_field%22:%22MYSQL%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:27] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:27] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:35] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:35] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:44] "POST /assets/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:45] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:36:45] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:38:03] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:38:03] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:38:03] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:39:19] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:39:19] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:39:19] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:42:23] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:42:23] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:42:23] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:42:31] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:42:31] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:42:31] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:43:29] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:43:29] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
(pymysql.err.InternalError) (1366, "Incorrect integer value: '多对多' for column 'ssh_port' at row 1") [SQL: 'INSERT INTO assets_hosts (name, `desc`, type, zone, docker_uri, ssh_ip, ssh_port) VALUES (%(name)s, %(desc)s, %(type)s, %(zone)s, %(docker_uri)s, %(ssh_ip)s, %(ssh_port)s)'] [parameters: {'name': '订单', 'desc': '订单', 'type': '多对多', 'zone': '公司环境', 'docker_uri': '订单', 'ssh_ip': '多对多', 'ssh_port': '多对多'}]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1366, "Incorrect integer value: '多对多' for column 'ssh_port' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/assets/host.py", line 46, in post
    host.save()
  File "/opt/samba/xdata/xdata/xdata_api/libs/model.py", line 20, in save
    db_session_commit()
  File "/opt/samba/xdata/xdata/xdata_api/libs/model.py", line 6, in db_session_commit
    db.session.commit()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 856, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1057, in _read_query_result
    result.read()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1340, in read
    first_packet = self.connection._read_packet()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1014, in _read_packet
    packet.check_error()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1366, "Incorrect integer value: '多对多' for column 'ssh_port' at row 1") [SQL: 'INSERT INTO assets_hosts (name, `desc`, type, zone, docker_uri, ssh_ip, ssh_port) VALUES (%(name)s, %(desc)s, %(type)s, %(zone)s, %(docker_uri)s, %(ssh_ip)s, %(ssh_port)s)'] [parameters: {'name': '订单', 'desc': '订单', 'type': '多对多', 'zone': '公司环境', 'docker_uri': '订单', 'ssh_ip': '多对多', 'ssh_port': '多对多'}]
127.0.0.1 - - [19/Sep/2018 10:43:44] "POST /assets/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:43:52] "POST /assets/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:43:52] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:43:52] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:47:22] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:47:22] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:47:22] "GET /users/hosts/type/ HTTP/1.1" 200 -
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
name 'AppHostRel' is not defined
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 74, in delete
    if AppHostRel.query.filter_by(host_id=host_id).first():
NameError: name 'AppHostRel' is not defined
127.0.0.1 - - [19/Sep/2018 10:47:29] "DELETE /users/hosts/5 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:47:40] "GET /users/hosts/5/extend/ HTTP/1.1" 404 -
127.0.0.1 - - [19/Sep/2018 10:49:01] "PUT /users/hosts/5 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:01] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:01] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:01] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:15] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:15] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:15] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:41] "POST /users/hosts/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:41] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:41] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:49:41] "GET /users/hosts/type/ HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 10:51:06] "DELETE /users/hosts/3 HTTP/1.1" 404 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
host_ng {'page': 1, 'pagesize': 10, 'host_query': {'name_field': '', 'zone_field': ''}}
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
--------------------------------------------------------------------------------
ERROR in middleware [/opt/samba/xdata/xdata/xdata_api/libs/middleware.py:40]:
name 'AppHostRel' is not defined
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/samba/xdata/xdata/xdata_api/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/samba/xdata/xdata/xdata_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/opt/samba/xdata/xdata/xdata_api/apps/users/host.py", line 51, in delete
    if AppHostRel.query.filter_by(host_id=host_id).first():
NameError: name 'AppHostRel' is not defined
172.16.6.253 - - [19/Sep/2018 10:51:36] "DELETE /users/hosts/6 HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
172.16.6.253 - - [19/Sep/2018 10:54:46] "DELETE /users/hosts/6 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:54:51] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:54:51] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:54:51] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:54:52] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 10:55:14] "DELETE /users/hosts/4 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:55:26] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 10:55:34] "DELETE /users/hosts/4 HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/assets/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [19/Sep/2018 13:13:39] "POST /account/users/login/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 13:13:40] "GET /home/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 13:13:42] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 13:13:42] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 13:13:42] "GET /users/hosts/type/ HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/libs/utils.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
172.16.6.253 - - [19/Sep/2018 14:35:44] "GET /users/hosts/4/valid HTTP/1.1" 401 -
172.16.6.253 - - [19/Sep/2018 14:36:05] "GET /users/hosts/4/valid HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 14:36:20] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:03] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:14] "PUT /users/hosts/4 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:15] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:15] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:15] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:18] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:18] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:18] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:26] "PUT /users/hosts/4 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:26] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:26] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:26] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:27] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:34] "PUT /users/hosts/4 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:35] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:35] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:35] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:36] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:38] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:43] "PUT /users/hosts/4 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:43] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:43] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:43] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:44] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:46] "GET /users/hosts/5/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:37:54] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%E5%8D%8E%E4%B8%9C1%E5%8C%BA%22,%22type_field%22:%22MYSQL%22%7D HTTP/1.1" 200 -
 * Detected change in '/opt/samba/xdata/xdata/xdata_api/apps/users/host.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 286-050-437
127.0.0.1 - - [19/Sep/2018 14:38:44] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:38:45] "GET /users/hosts/5/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 14:38:47] "GET /users/hosts/4/valid HTTP/1.1" 200 -
172.16.6.253 - - [19/Sep/2018 14:38:53] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:09:42] "GET /users/hosts/4/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:09:44] "GET /users/hosts/5/valid HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:20:34] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%E5%8D%8E%E4%B8%9C1%E5%8C%BA%22,%22type_field%22:%22MYSQL%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:21:38] "GET /assets/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:21:38] "GET /assets/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:21:43] "GET /users/hosts/?page=1&host_query=%7B%22name_field%22:%22%22,%22zone_field%22:%22%22%7D HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:21:43] "GET /users/hosts/zone/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:21:43] "GET /users/hosts/type/ HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:21:55] "GET /users/hosts/4/extend/ HTTP/1.1" 404 -
127.0.0.1 - - [19/Sep/2018 15:21:57] "GET /users/hosts/4/extend/ HTTP/1.1" 404 -
127.0.0.1 - - [19/Sep/2018 15:22:06] "DELETE /users/hosts/4 HTTP/1.1" 200 -
127.0.0.1 - - [19/Sep/2018 15:22:11] "DELETE /users/hosts/4 HTTP/1.1" 200 -
